<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QvdSUAL</name>
    <message>
        <source>OK</source>
        <translation></translation>
    </message>
    <message>
        <source>NG</source>
        <translation></translation>
    </message>
    <message>
        <source>Defect Type: </source>
        <translation>缺陷类型：</translation>
    </message>
    <message>
        <source>diaojiao</source>
        <translation>掉角</translation>
    </message>
    <message>
        <source>huahen</source>
        <translation>划痕</translation>
    </message>
    <message>
        <source>zangwu</source>
        <translation>脏污</translation>
    </message>
    <message>
        <source>Area/Contrast</source>
        <translation>面积/对比度</translation>
    </message>
    <message>
        <source>Length</source>
        <translation>长度</translation>
    </message>
    <message>
        <source>Width</source>
        <translation>宽度</translation>
    </message>
</context>
<context>
    <name>QvdSUALPlugin</name>
    <message>
        <source>SUAL</source>
        <translation>数优接口</translation>
    </message>
    <message>
        <source>Describe</source>
        <translation>描述</translation>
    </message>
</context>
<context>
    <name>vdsual</name>
    <message>
        <source>rdoSetting</source>
        <translation>设置</translation>
    </message>
    <message>
        <source>rdoInspect</source>
        <translation>检测</translation>
    </message>
    <message>
        <source>calibration_type</source>
        <translation>相机类型</translation>
    </message>
    <message>
        <source>camera1</source>
        <translation>相机1</translation>
    </message>
    <message>
        <source>camera2</source>
        <translation>相机2</translation>
    </message>
    <message>
        <source>camera3</source>
        <translation>相机3</translation>
    </message>
    <message>
        <source>camera4</source>
        <translation>相机4</translation>
    </message>
    <message>
        <source>camera5</source>
        <translation>相机5</translation>
    </message>
    <message>
        <source>camera6</source>
        <translation>相机6</translation>
    </message>
    <message>
        <source>camera7</source>
        <translation>相机7</translation>
    </message>
    <message>
        <source>camera8</source>
        <translation>相机8</translation>
    </message>
    <message>
        <source>camera9</source>
        <translation>相机9</translation>
    </message>
    <message>
        <source>isEdge</source>
        <translation>缺角</translation>
    </message>
    <message>
        <source>port1</source>
        <translation>默认</translation>
    </message>
    <message>
        <source>port2</source>
        <translation>端口1</translation>
    </message>
    <message>
        <source>port3</source>
        <translation>端口2</translation>
    </message>
    <message>
        <source>port4</source>
        <translation>端口3</translation>
    </message>
    <message>
        <source>port5</source>
        <translation>端口4</translation>
    </message>
    <message>
        <source>port6</source>
        <translation>端口5</translation>
    </message>
    <message>
        <source>port7</source>
        <translation>端口6</translation>
    </message>
    <message>
        <source>port8</source>
        <translation>端口7</translation>
    </message>
    <message>
        <source>port9</source>
        <translation>端口8</translation>
    </message>
    <message>
        <source>isScratch</source>
        <translation>划痕</translation>
    </message>
    <message>
        <source>isMudge</source>
        <translation>脏污</translation>
    </message>
</context>
</TS>
